### ISSUE TITLE
could you share your trained weight?

### ISSUE THREAD

**Issue by Dongshengjiang** [tuvovan/Zero_DCE_TF#2]
could you share your trained weight?

**Comment by tuvovan** [comment]
hi, thank you for interest on my repo. 
I tried to upload the weight to my driver after pushing this repo but now I don't manage to find it.

Please follow the procedure on README file, I believe you can get the same results as mine.

Happy training! 💯

**Comment by Dongshengjiang** [comment]
ok, thanks!
