### ISSUE TITLE
much brighter output image by my trained weights than the one produced by your net weights

### ISSUE THREAD

**Issue by huntkao** [tuvovan/Zero_DCE_TF#4]
Thanks for share the implementation.

  When I use the model which was trained myself following the training step (using SICE part1 dataset), my output
  images were quite bright (at ~50th epoch). For example, the sky area of daytime became nearly over-exposed.

  Do you have any idea for possible reason?

  Thank you

**Comment by tuvovan** [comment]
Would you mind sharing your output and my output?
