### ISSUE TITLE
Several questions about the code.

### ISSUE THREAD

**Issue by Yi-Hung-Sung** [tuvovan/Zero_DCE_TF#5]
Thank you to provide such an excellent code. I'm new to python, I have several questions about the code.

For the code in train.py:
At line 88,written : "r1, r2, r3, r4, r5, r6, r7, r8 = A[:,:,:,:3], A[:,:,:,3:6], A[:,:,:,6:9], A[:,:,:,9:12], A[:,:,:,12:15], A[:,:,:,15:18], A[:,:,:,18:21], A[:,:,:,21:24]".  
   
1.What is the meaning of A[:,:,:,:3], A[:,:,:,3:6] and so on? 
2.Do these correspond to split image to R、G、B channel? 
3.If not, where's the code that split image to R、G、B channel?

**Comment by tuvovan** [comment]
Please follow the details in the paper. Those are intermediate output of the network!
